# Generated by Django 4.1.1 on 2023-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('item', models.ManyToManyField(to='main.item')),
            ],
        ),
    ]
